In [30]:
import numpy as np

In [32]:
my_list = [0,1,2,3,4]

In [34]:
my_list

[0, 1, 2, 3, 4]

In [36]:
arr = np.array(my_list)
type(arr)

numpy.ndarray

In [38]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [40]:
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

In [42]:
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [44]:
np.ones((2,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [46]:
np.random.seed(55)
arr = np.random.randint(0,100,10)

In [48]:
arr

array([77, 26, 39, 72, 29, 61, 55, 37, 91, 33])

In [50]:
arr2 = np.random.randint(0,100,10)

In [52]:
arr2

array([54, 35, 46, 94, 61, 77, 94, 12, 24, 71])

In [54]:
arr.max()

91

In [55]:
arr.min()

26

In [56]:
arr.mean()

52.0

In [57]:
arr.argmin()

1

In [58]:
arr.argmax()

8

In [61]:
arr.reshape(2,5)

array([[77, 26, 39, 72, 29],
       [61, 55, 37, 91, 33]])

In [62]:
arr.shape

(10,)

In [64]:
arr = arr.reshape(2,5)
arr.shape

(2, 5)

In [65]:
mat = np.arange(0,100).reshape(10,10)

In [66]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [67]:
row = 0
col = 1
mat[0,1]

1

In [68]:
mat[:,col]

array([ 1, 11, 21, 31, 41, 51, 61, 71, 81, 91])

In [69]:
mat[row,:]

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [71]:
mat[row,:].reshape(10,1)

array([[0],
       [1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8],
       [9]])

In [72]:
mat[0:3,0:3]

array([[ 0,  1,  2],
       [10, 11, 12],
       [20, 21, 22]])

In [73]:
mat[0:3,0:3] = 0

In [74]:
mat

array([[ 0,  0,  0,  3,  4,  5,  6,  7,  8,  9],
       [ 0,  0,  0, 13, 14, 15, 16, 17, 18, 19],
       [ 0,  0,  0, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [76]:
mynewmat = mat.copy()
mynewmat[0:6,:] = 0

In [77]:
mynewmat

array([[ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [78]:
mat

array([[ 0,  0,  0,  3,  4,  5,  6,  7,  8,  9],
       [ 0,  0,  0, 13, 14, 15, 16, 17, 18, 19],
       [ 0,  0,  0, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])